### ISSUE TITLE
System.Exception: GetDecryptionFunction failed

### ISSUE THREAD

**Issue by lalernehl** [omansak/libvideo#102]
Executing this code on a thread (async task):

var youTube = VideoLibrary.YouTube.Default;
var videoMetadata = await youTube.GetVideoAsync(video.Metadata.PlayUrl);
await File.WriteAllBytesAsync(Path.Combine(downloadPath, video.Filename), videoMetadata.GetBytes());

...will download a few videos and eventually hang. I haven't reproduced the issue on a debugging computer but it seems like the thread will hag and stop downloading or even failing. I must say that I'm not sure if the hanging is related to this exception.

System.Exception: GetDecryptionFunction failed
   at VideoLibrary.YouTubeVideo.GetDecryptionFunction(String js)
   at VideoLibrary.YouTubeVideo.GetDecryptionFunctionLines(String js)
   at VideoLibrary.YouTubeVideo.DecryptSignature(String js, String signature)
   at VideoLibrary.YouTubeVideo.<DecryptAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.YouTubeVideo.<GetUriAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.VideoClient.<GetBytesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.Video.<GetBytesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.Video.GetBytes()
   at VideoDownloader.VideoManager.<DownloadAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoDownloader.Program.<>c__DisplayClass3_0.<<GetDownloadVideosThread>b__0>d.MoveNext()

**Comment by omansak** [comment]
#98

**Comment by ConfusedRunningGuy** [comment]
I'm still getting the same error System.Exception: GetDecryptionFunction failed

**Comment by omansak** [comment]
#103 test and feedback.

**Comment by SoftwareMagicIT** [comment]
I tested: system collection generic key not found exception in query.cs issue

**Comment by omansak** [comment]
@fabcal24 i dont see any problem

**Comment by ConfusedRunningGuy** [comment]
Oh man @omansak you are brilliant.  It worked.  I don't know how you did it.  But you did it.  Thank you so much.

**Comment by omansak** [comment]
@ConfusedRunningGuy #103 is updated service and my service is not reliable pls use your own service

**Comment by karamba121** [comment]
@omansak I tested but I'm still getting the same error System.Exception: GetDecryptionFunction failed at youtube url https://youtu.be/aw52gv2OEV8

**Comment by hig-dev** [comment]
My fork is working: https://github.com/hig-dev/libvideo
NuGet: https://www.nuget.org/packages/VideoLibraryHIG/

**Comment by Daniel-Majunke** [comment]
I Love You, is work !!

**Comment by omansak** [comment]
@hig-dev please read licence

**Comment by karamba121** [comment]
@hig-dev you are awsome! Thanks bro.

**Comment by akcorp2003** [comment]
@hig-dev For these videos: 
https://www.youtube.com/watch?v=SdHQkkRc-hc.
https://www.youtube.com/watch?v=LNArCBr6rrs

Occasionally, in debug mode they sometimes work, sometimes hang. However, when I run a release build on my custom app, it always hangs. I have created a new app just to see if it's a config issue but no luck. 

I'm on VS 2015 if that makes a difference.

**Comment by hig-dev** [comment]
@akcorp2003 On what platform do you have the problem? I tested the videos on my UWP App and it did work flawlessly.

**Comment by akcorp2003** [comment]
@hig-dev I am targeting .NET 4.6.1 for a WPF application.

**Comment by kotharijk** [comment]
I am using following nuget package https://www.nuget.org/packages/VideoLibraryHIG/. I am getting error. Any help will be highly appreciated.

"System.Exception
  HResult=0x80131500
  Message=Could not find the entry function for signature deciphering.
  Source=libvideo
  StackTrace:
   at VideoLibrary.YouTubeVideo.DecryptedSignature(String signature, String js)
   at VideoLibrary.YouTubeVideo.<DecryptAsync>d__19.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.YouTubeVideo.<GetUriAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.VideoClient.<GetBytesAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.Video.<GetBytesAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.Video.GetBytes()
   at YouTubeAudioExtractor.frmYouTubeAudioExtractor.BtnCreateMP3MediaToolkit_Click(Object sender, EventArgs e) in C:\JKK\Projects\YouTubeAudioExtractor\YouTubeAudioExtractor\frmMain.cs:line 38
"
