### ISSUE TITLE
GetEncryptionFunction Fails on some videos now

### ISSUE THREAD

**Issue by mbparker** [omansak/libvideo#113]
I get a stack trace similar to this:

System.AggregateException: One or more errors occurred. ---> System.Exception: GetDecryptionFunction failed
   at VideoLibrary.YouTubeVideo.GetDecryptionFunction(String js)
   at VideoLibrary.YouTubeVideo.GetDecryptionFunctionLines(String js)
   at VideoLibrary.YouTubeVideo.DecryptSignature(String js, String signature)
   at VideoLibrary.YouTubeVideo.<DecryptAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.YouTubeVideo.<GetUriAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VideoLibrary.YouTubeVideo.get_Uri()

Example video: https://www.youtube.com/watch?v=-F7A24f6gNc

**Note that this video worked just a few days ago.**

**Comment by omansak** [comment]
Update Regex Function in YouTubeVideo.Decrypt

\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*([a-zA-Z0-9$]+)\(

Credit : https://github.com/Tyrrrz/YoutubeExplode/commit/27a4a421c14705fd98f59db71ec3cd379ab1e046

or

\((\w+)\(\([a-zA-Z0-9$]*,window.decodeURIComponent\)\(\w+\)\)\)

Credit : @omansak 


or you can use my fork with dynamic regex service : 
https://github.com/omansak/libvideo

**Comment by mbparker** [comment]
@omansak Thank you. 

Also need to update GetDecryptionFunction to return the first group value, but that regex did the trick.

GetDecryptionFunction...
return match.Groups[*1*].Value;

**Comment by K0ST4S** [comment]
Nuget release please

**Comment by hig-dev** [comment]
@CodeBlackSmith You can use the NuGet of my fork: https://www.nuget.org/packages/VideoLibraryHIG/
@mbparker You should not close the issue until it is fixed here.

**Comment by mbparker** [comment]
Re-opening issue, since it is not fixed in this repo.

**Comment by mbparker** [comment]
> @mbparker You should not close the issue until it is fixed here.

@hig-dev  Agreed.

**Comment by okutbay** [comment]
Cloned the source code and applied all fixes above, still having the exception. Did not get what is wrong :(

        public byte[] GetBytes() =>
            GetBytesAsync().GetAwaiter().GetResult();

System.Exception: 'GetDecryptionFunction failed'

System.Exception
  HResult=0x80131500
  Message=GetDecryptionFunction failed
  Source=libvideo
  StackTrace:
   at VideoLibrary.YouTubeVideo.GetDecryptionFunction(String js) in C:\Sources\MP3Head\libvideo-master\src\libvideo\YouTubeVideo.Decrypt.cs:line 90
   at VideoLibrary.YouTubeVideo.GetDecryptionFunctionLines(String js) in C:\Sources\MP3Head\libvideo-master\src\libvideo\YouTubeVideo.Decrypt.cs:line 67
   at VideoLibrary.YouTubeVideo.DecryptSignature(String js, String signature) in C:\Sources\MP3Head\libvideo-master\src\libvideo\YouTubeVideo.Decrypt.cs:line 36
   at VideoLibrary.YouTubeVideo.<DecryptAsync>d__21.MoveNext() in C:\Sources\MP3Head\libvideo-master\src\libvideo\YouTubeVideo.Decrypt.cs:line 30
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.YouTubeVideo.<GetUriAsync>d__13.MoveNext() in C:\Sources\MP3Head\libvideo-master\src\libvideo\YouTubeVideo.cs:line 40
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.VideoClient.<GetBytesAsync>d__10.MoveNext() in C:\Sources\MP3Head\libvideo-master\src\libvideo\VideoClient.cs:line 73
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.Video.<GetBytesAsync>d__11.MoveNext() in C:\Sources\MP3Head\libvideo-master\src\libvideo\Video.cs:line 32
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VideoLibrary.Video.GetBytes() in C:\Sources\MP3Head\libvideo-master\src\libvideo\Video.cs:line 26
   at MP3Head.App.Program.Main(String[] args) in C:\Sources\MP3Head\MP3Head.App\Program.cs:line 64

**Comment by omansak** [comment]
@okutbay you need change regex in Youtube.Decrypt.  https://github.com/i3arnon/libvideo/issues/113#issuecomment-436684603

**Comment by okutbay** [comment]
> 
> 
> @okutbay you need change regex in Youtube.Decrypt. [#113 (comment)](https://github.com/i3arnon/libvideo/issues/113#issuecomment-436684603)

Yep already did it.

**Comment by omansak** [comment]
@okutbay and you need change regex group 1 from 3 https://github.com/i3arnon/libvideo/blob/53af4b2915349012573003576997022ebd374ceb/src/libvideo/YouTubeVideo.Decrypt.cs#L87

**Comment by okutbay** [comment]
> 
> 
> @okutbay and you need change regex group 1 from 3
> 
> [libvideo/src/libvideo/YouTubeVideo.Decrypt.cs](https://github.com/i3arnon/libvideo/blob/53af4b2915349012573003576997022ebd374ceb/src/libvideo/YouTubeVideo.Decrypt.cs#L87)
> 
> Line 87 in [53af4b2](/i3arnon/libvideo/commit/53af4b2915349012573003576997022ebd374ceb)
>  return match.Groups[3].Value;

Yes i did that too. I really did not get what is wrong. I decided to use nuget package of @hig-dev

**Comment by i3arnon** [comment]
Should be fixed with [v2.0.3](https://www.nuget.org/packages/VideoLibrary/2.0.3)
Please reopen the issue if that's not the case.
