### ISSUE TITLE
Still Getting System.Exception: Get DecryptionFunction failed

### ISSUE THREAD

**Issue by antfusa** [omansak/libvideo#131]
Video Library Version: 2.0.3 (11/17/2018) pulled via NugetPackage Manager
Example URL: https://www.youtube.com/watch?v=fSOBj2DTuV8

The following Error is thrown: (Oddly enough this happens to some videos, but not all)

System.Exception: GetDecryptionFunction failed
   at VideoLibrary.YouTubeVideo.GetDecryptionFunction(String js)
   at VideoLibrary.YouTubeVideo.GetDecryptionFunctionLines(String js)
   at VideoLibrary.YouTubeVideo.DecryptSignature(String js, String signature)
   at VideoLibrary.YouTubeVideo.<DecryptAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.YouTubeVideo.<GetUriAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.VideoClient.<GetBytesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.Video.<GetBytesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.Video.GetBytes()
   at MyTube.Form2.DownloadVideo(String URL, String Path) in C:\Users\WinUser\Source\repos\MyTube\MyTube\Form2.cs:line 69

I know this issue has come up before on here, but those are from much older versions so I was not sure if they are still relevant fixes or not. Please Advise.

**Comment by omansak** [comment]
@antfusa test my last commit #125 (https://github.com/omansak/libvideo)

**Comment by yoirgl** [comment]
> 
> 
> @antfusa test my last commit #125 (https://github.com/omansak/libvideo)

Hey there. I tried your commit and while the decryption works i get a 403 forbidden on video.GetBytes()
Any idea ?

**Comment by lnickdnguyen** [comment]
How do I pull in your new commit? Is it updated in the nuget v2.0.3 package? Still getting the "GetDecryptionFunction Failed" exception. @omansak

**Comment by omansak** [comment]
@lnickdnguyen download and build https://github.com/omansak/libvideo

**Comment by Jikari** [comment]
I'm getting the same exception with @omansak 's branch

**Comment by omansak** [comment]
Fixed. Update 3.0.0

**Comment by JesWhite** [comment]
how can i download libvideo 3.0?

**Comment by omansak** [comment]
@JesWhite Nuget or non-build version on github

**Comment by JesWhite** [comment]
Really i dont know nuget. i need .exe only
