### ISSUE TITLE
Video with hyphen in video ID doesn't work

### ISSUE THREAD

**Issue by mphacker** [omansak/libvideo#137]
If I try to pass in a URL that has a video ID which has a hyphen it throws an error: 
 System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at VideoLibrary.Helpers.Query.get_Item(String key)
   at VideoLibrary.YouTube.Unscramble(String queryString)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at VideoLibrary.YouTube.<ParseVideos>d__6.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at VideoLibrary.ServiceBase`1.VideoSelector(IEnumerable`1 videos)
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__6.MoveNext()

Sample video with the issue: https://www.youtube.com/watch?v=V9-oZtSZBcc

**Comment by omansak** [comment]
Fixed. Update 3.0.0
