### ISSUE TITLE
YouTube Error 429 appears after a while

### ISSUE THREAD

**Issue by Win8Error** [omansak/libvideo#150]
After a while the library crashes because YouTube only throws error 429 back.

Can I somehow work around this error?

```
System.Net.Http.HttpRequestException: Der Antwortstatuscode gibt keinen Erfolg an: 429 (Too Many Requests).
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   bei VideoLibrary.YouTube.<GetAllVideosAsync>d__5.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   bei VideoLibrary.ServiceBase`1.<GetVideoAsync>d__6.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   bei VideoLibrary.ServiceBase`1.<GetVideoAsync>d__5.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei VideoLibrary.ServiceBase`1.GetVideo(String videoUri)
   bei Klient.Tools.YouTubeTools.IstURLValide(String _URL) in C:\Users\Joel Burgio\source\repos\YouTube Downloader\Klient\Tools\YouTubeTools.cs:Zeile 12.

```
<img width="694" alt="Screenshot1" src="https://user-images.githubusercontent.com/10245525/74780058-1db68500-529f-11ea-9e7c-566f3aef7d77.PNG">
<img width="690" alt="Screenshot2" src="https://user-images.githubusercontent.com/10245525/74780061-1f804880-529f-11ea-8581-daa8defa03e7.PNG">

**Comment by omansak** [comment]
How did u use VideoLibrary ?

**Comment by ruhhh** [comment]
I used to have the same problem when I used youtube-dl for Python and now I get the same error using this Library. I think the problem is basically just that Youtube temporarily blocked your IP because you sent too many requests in a certain timeframe. However in some cases (like mine) it seems to be permanent. Sometimes these bans/blocks seem to be kind of random though.

Basically what happens is that Youtube detects that your IP is blocked and tells you to solve a captcha which you obviously can't do when you're downloading the video from a function. You can test this by opening your browser in incognito mode and then trying to open a video by URL (not by opening Youtube homepage and clicking on random video). Youtube should prompt you to solve a captcha. Some people in the youtube-dl issues mentioned that doing this and solving the captcha in the browser solved the problem for them but for me and some others it doesn't seem to work.

For youtube-dl there is a workaround where you download your cookies from your browser and include them as .txt in the call to youtube-dl. I am not sure how it actually integrates your cookies in the request but it fixes the problem.

It is definitely not this library's fault that you are getting the error. You can test this out by connecting to a proxy and then running your function again and it should work (unless the proxy's IP is blocked too ofc). I just tried it out with a proxy and it works perfectly fine.

If the devs of this library are willing to integrate a similar solution to the youtube-dl one, I could look into how they are using the cookies in their requests whenever I have some spare time and give an update.

**Comment by omansak** [comment]
Outdated.

**Comment by alefsoft1** [comment]
I have the same problem. I get "Too Many Requests"!
Details: 

System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=Response status code does not indicate success: 429 (Too Many Requests).
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.YouTube.<GetAllVideosAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VideoLibrary.ServiceBase`1.GetVideo(String videoUri)
   at .Form1.<button6_Click>d__8.MoveNext() in \Form1.cs:line 205

  This exception was originally thrown at this call stack:
    [External Code]
   Form1.button6_Click(object, System.EventArgs) in Form1.cs

**Comment by alefsoft1** [comment]
I use latest videolibrary.
