### ISSUE TITLE
Error while copying content to a stream. The specified data could not be decrypted

### ISSUE THREAD

**Issue by iUnstable0** [omansak/libvideo#181]
https://i.imgur.com/dbLhJ9D.png

it gave me this error when I try to download the video.
In some videos, it works but in some videos throws this error.

Edit: Sometime youtu.be works but youtube.com/watch?v= doesn't work. and vise versa
sometimes it works sometimes it doesn't work too

Full details

System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=Error while copying content to a stream.
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.VideoClient.<GetBytesAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.Video.<GetBytesAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VideoLibrary.Video.GetBytes()
   at Youtube_Video_Downloader.Form1.DownloadButton_Click(Object sender, EventArgs e) in C:\Users\mamip\source\repos\Youtube Video Downloader\Youtube Video Downloader\Form1.cs:line 68
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Youtube_Video_Downloader.Program.Main() in C:\Users\mamip\source\repos\Youtube Video Downloader\Youtube Video Downloader\Program.cs:line 19

Inner Exception 1:
IOException: The decryption operation failed, see inner exception.

Inner Exception 2:
Win32Exception: The specified data could not be decrypted

**Comment by omansak** [comment]
Did you use last version ?

**Comment by iUnstable0** [comment]
> Did you use last version ?

yep i just checked now no new version I'm on version 3.0.8 
https://i.imgur.com/b63dqo5.png

**Comment by omansak** [comment]
can you share youtube id ?

**Comment by iUnstable0** [comment]
what do you mean youtube id? sorry for responding late 🍡

**Comment by iUnstable0** [comment]
It’s not solved why did you close this !

**Comment by omansak** [comment]
can you test on last versions ? @happygagarara12

**Comment by dkroye** [comment]
@omansak Tested and appears to be fixed. Thank you!

**Comment by iUnstable0** [comment]
yes it is fixed, thank you!!!
