### ISSUE TITLE
Parameter "str" value cannot be null

### ISSUE THREAD

**Issue by Vesper-Works** [omansak/libvideo#188]
My program has been working fine until recently. When doing "youTube.GetVideo" or "await youTube.GetVideoAsync" for any valid YouTube link this error arises:

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: str
  Source=System
  StackTrace:
   at System.Text.RegularExpressions.Regex.Unescape(String str)
   at VideoLibrary.YouTube.<ParseVideos>d__7.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at VideoLibrary.ServiceBase`1.VideoSelector(IEnumerable`1 videos)
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ImageToASCII.Form1.<DownloadYouTubeVideo>d__11.MoveNext() in F:\ImageToASCII\Form1.cs:line 96

  This exception was originally thrown at this call stack:
    System.Text.RegularExpressions.Regex.Unescape(string)
    VideoLibrary.YouTube.ParseVideos(string)
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
    ImageToASCII.Form1.DownloadYouTubeVideo(string) in Form1.cs
```

In another project of mine, I think I'm using YouTube explode for audio, the library has stopped working also. Purhaps YouTube has changed something themselves? 
Thanks

**Comment by omansak** [comment]
Does this still occur?

**Comment by Vesper-Works** [comment]
> Does this still occur?

Yes.
Here is the exact code I'm using, and the link:
```
private async void DownloadYouTubeVideo(string link)
        {           
            var youTube = YouTube.Default;  
            var video = await youTube.GetVideoAsync(link);
            var bytes = await video.GetBytesAsync();
            File.WriteAllBytes(Path.Combine(Application.StartupPath, video.FullName), bytes);
            selectedVideoPath = Path.Combine(Application.StartupPath, video.FullName);
            TextForm textForm = new TextForm(selectedVideoPath, CompressionSlider.Value, InvertColours.Checked, visualiseFrames.Checked, FPSperfect.Checked, font);
            textForm.Show();
        }
```
https://www.youtube.com/watch?v=7TJvqYvJ9oM&ab_channel=BlastingCompany

The error flags on the line "var video = await youTube.GetVideoAsync(link);".

**Comment by omansak** [comment]
this video has  age-restricted

**Comment by Vesper-Works** [comment]
I get the error regardless of whether or not it's age-restricted.

I've just now updated to version 3.0.9 and the issue seems to be resolved thankfully.
Thanks for your time, and sorry I didn't check for the latest version sooner.
