### ISSUE TITLE
Additional text encountered after finished reading JSON content

### ISSUE THREAD

**Issue by gasand** [omansak/libvideo#250]
Hi there! Thanks for the grat tool!
I've encountered this error trying to download some YouTube videos...
Try for example with video:  dFrGOddNg_Y

Hope this helps!

[08:51:23 FTL] Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: ;. Path '', line 1, position 66369.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json)
   at VideoLibrary.YouTube.<ParseVideos>d__8.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at VideoLibrary.ServiceBase`1.VideoSelector(IEnumerable`1 videos)
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

........

**Comment by hondek** [comment]
Hi,

I sent pull request fixing this problem.
