### ISSUE TITLE
Video cannot be retrieved - UnavailableStreamException

### ISSUE THREAD

**Issue by kizuki1749** [omansak/libvideo#289]
In the latest version 3.2.5, it is no longer possible to retrieve videos from YouTube using GetAllVideosAsync().

An exception called UnavailableStreamException is thrown for all videos, and the message “Error caused by YouTube. (This video is not available)” is displayed.

I wonder if this is due to a change in YouTube's specifications.

![スクリーンショット 2024-09-27 014121](https://github.com/user-attachments/assets/ebe5527b-dd07-4768-94fe-61fee71f361e)

**Comment by crazybmanp** [comment]
I am also getting this error

**Comment by MickeCast** [comment]
I was using an old version and I started getting the forbidden error, then I updated the nuget package for c# visual studio, and I started getting this same error (Error caused by Youtube.(This video is not available))), but when calling the GetVideo method:
`var youTube = YouTube.Default; 
    var video = youTube.GetVideo("https://www.youtube.com/watch?v=" + videoId);`

It fails for any video id, but in my case I am testing with this id: S2tZS-vNMTM

Wondering if this is youtube changing something, or a just a bug on the library. @omansak any advice would be very appreciated.

Stacktrace:
`   at VideoLibrary.YouTube.<ParseVideos>d__9.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at VideoLibrary.ServiceBase`1.VideoSelector(IEnumerable`1 videos)
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VideoLibrary.ServiceBase`1.GetVideo(String videoUri)
   at <DownloadAndUploadVideo>d__19.MoveNext()

**Comment by hady-khann** [comment]
![yt](https://github.com/user-attachments/assets/aa1c7c25-157e-4b1f-9e2a-e450989b9b8a)

i'm getting same error

**Comment by crazybmanp** [comment]
Gonna cross post this ticket from another repo, they had the same issue. The fix doesn't seem to work fully for them, but there could be something useful in this discussion. https://github.com/Tyrrrz/YoutubeExplode/issues/817

**Comment by SteveW400** [comment]
I'm getting the same problem. On multiple files, the URLs work OK when pasted directly into a browser.
Two weeks ago, it worked OK. Since then, Widows has been updated including Edge and the WebView2 runtime. I don't see anything else that changed.

**Comment by ricovivid** [comment]
I'm getting it on all youtube URLs as well. Was working a couple days ago. My program is a .NET MAUI app.

**Comment by kizuki1749** [comment]
I tried testing the PR, but it still seems to be unable to retrieve the video.

**Comment by SteveW400** [comment]
SharpGrabber has the same problem https://github.com/dotnettools/SharpGrabber/issues/99 
Looks like something changed at YouTube.

**Comment by Aequitas00** [comment]
When testing the pr do you all get the same error? When i made the change i tested in the libvideo Program file.

**Comment by SteveW400** [comment]
9/29/2024 4:39:33 PM Info Url = https://www.youtube.com/watch?v=WtkjyIaJDTE
9/29/2024 4:39:34 PM ERROR VideoLibrary.Exceptions.UnavailableStreamException: Error caused by Youtube.(This video is not available))
   at VideoLibrary.YouTube.<ParseVideos>d__9.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at VideoLibrary.ServiceBase`1.VideoSelector(IEnumerable`1 videos)
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at VideoLibrary.ServiceBase`1.<GetVideoAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VideoLibrary.ServiceBase`1.GetVideo(String videoUri)
   at SoundAnalysis.ImagingWhiteboard.Controls.YouTubeInputControl.YouTubeWebBrowser_SourceChanged(Object sender, CoreWebView2SourceChangedEventArgs e)

**Comment by SteveW400** [comment]
omansak, thanks 3.2.6 works perfectly.
