### ISSUE TITLE
Getting a System.OutOfMemoryException when running video.GetBytes()?

### ISSUE THREAD

**Issue by ccooper4** [omansak/libvideo#79]

**Comment by i3arnon** [comment]
Hey @ccooper4,
Could post the video url and code you use that you get this exception with?
It could be that the video is just too big for your memory to handle, but maybe there are some inefficient things being done that I can optimize.

**Comment by noorphish** [comment]
Hello,
same Error in my case.

Try to download this video: URL deleted

My Code:
`
Private Sub YouTubeVideoDownload(ByVal strLink As String)
        Dim video = VideoLibrary.YouTube.Default.GetVideo(strLink)
        File.WriteAllBytes("D:\" & video.FullName, video.GetBytes())
End Sub`

**Comment by noorphish** [comment]
Can we expect a fix to solve the problem, or is my code false?

**Comment by noorphish** [comment]
Please check this Sub:

Private Sub YouTubeVideoDownload(ByVal strLink As String)
        Dim intBytes As Integer
        Dim stream As Stream
        Dim byteBuffer(1024 * 1024) As Byte
        Dim video As VideoLibrary.YouTubeVideo = VideoLibrary.YouTube.Default.GetVideo(strLink)
        Using sw As New FileStream("D:\" & video.FullName, FileMode.Create, FileAccess.Write, FileShare.None)
            stream = video.Stream()
            Do
                intBytes = stream.Read(byteBuffer, 0, byteBuffer.Length)
                If intBytes = 0 Then
                    Exit Do
                Else
                    sw.Write(byteBuffer, 0, intBytes)
                End If
            Loop
        End Using
    End Sub

**Comment by PhyrexianHulk** [comment]
I'm getting the same exception using a github project that makes use of VideoLibrary v2.0.3.
Seems to only happen with specific urls:
failing url: https://www.youtube.com/watch?v=8kxzwHlm1gM

code i'm using:
https://github.com/maythamfahmi/YouTuber

running the : YouTuber.Console project

System.OutOfMemoryException
  HResult=0x8007000E
  Message=Exception of type 'System.OutOfMemoryException' was thrown.
  Source=mscorlib
  StackTrace:
   at System.IO.MemoryStream..ctor(Int32 capacity)
   at System.Net.Http.HttpContent.LimitMemoryStream..ctor(Int32 maxSize, Int32 capacity)
   at System.Net.Http.HttpContent.CreateMemoryStream(Int64 maxBufferSize, Exception& error)
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.VideoClient.<GetBytesAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.Video.<GetBytesAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.Video.GetBytes()
   at YouTuber.Client.YouTubeService.YoutubeToMp3(String url) in E:\visual studio 2015\Projects\YouTuber-master\YouTuber\Client\YouTubeService.cs:line 72
   at YouTuber.Client.YouTubeService.<>c__DisplayClass3_0.<YoutubeToMp3>b__0(String url) in E:\visual studio 2015\Projects\YouTuber-master\YouTuber\Client\YouTubeService.cs:line 25
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
